#!/usr/bin/env python3
"""
Replace the problematic heatmap with a clearer bar chart visualization
showing error propagation patterns.
"""

import json

with open('integration_paradox_demo.ipynb', 'r') as f:
    nb = json.load(f)

cell_idx = 42
cell = nb['cells'][cell_idx]
source = ''.join(cell['source'])
lines = source.split('\n')

# Find PAGE 5 (heatmap)
page5_start = None
page5_end = None
for i, line in enumerate(lines):
    if 'PAGE 5: ERROR PROPAGATION HEATMAP' in line:
        page5_start = i
        for j in range(i, min(i+100, len(lines))):
            if 'plt.close(fig)' in lines[j]:
                page5_end = j
                break
        break

if not page5_start or not page5_end:
    print("❌ Could not find PAGE 5")
    exit(1)

print(f"Found PAGE 5: lines {page5_start} to {page5_end}")

# Replace with a clearer bar chart visualization
new_visualization = '''    # PAGE 5: ERROR PROPAGATION PATTERNS (LANDSCAPE)
    # ========================================================================
    fig = plt.figure(figsize=(LETTER_HEIGHT, LETTER_WIDTH))

    # Create two subplots side by side
    ax1 = plt.subplot(1, 2, 1)
    ax2 = plt.subplot(1, 2, 2)

    fig.suptitle('Error Propagation Patterns Across SDLC Stages',
                fontsize=TITLE_SIZE, fontweight='bold',
                fontname=TITLE_FONT, color=TITLE_COLOR, y=0.96)

    # Chart 1: Error Generation by Stage
    stages = ['Requirements', 'Design', 'Implementation', 'Testing', 'Deployment']
    error_generation = {}
    error_reception = {}

    for stage in stages:
        error_generation[stage] = 0
        error_reception[stage] = 0

    if metrics.error_propagation:
        for error in metrics.error_propagation:
            source = error.get('source', '').lower()
            target = error.get('target', '').lower()

            # Count errors generated by each stage
            for stage in stages:
                if source == stage.lower():
                    error_generation[stage] += 1
                if target == stage.lower():
                    error_reception[stage] += 1

    # Plot 1: Errors Generated per Stage
    gen_values = [error_generation[s] for s in stages]
    bars1 = ax1.barh(range(len(stages)), gen_values,
                     color=['#e74c3c', '#e67e22', '#f39c12', '#f1c40f', '#2ecc71'],
                     alpha=0.8, edgecolor='black', linewidth=1.5)
    ax1.set_yticks(range(len(stages)))
    ax1.set_yticklabels(stages, fontsize=BODY_SIZE, fontname=BODY_FONT)
    ax1.set_xlabel('Errors Generated', fontsize=HEADING_SIZE, fontname=BODY_FONT, fontweight='bold')
    ax1.set_title('Error Generation by Stage', fontsize=HEADING_SIZE, fontname=BODY_FONT, fontweight='bold')
    ax1.grid(axis='x', alpha=0.3, linestyle='--')

    # Add value labels
    for i, (bar, val) in enumerate(zip(bars1, gen_values)):
        if val > 0:
            ax1.text(val + 0.5, i, str(int(val)),
                    va='center', fontsize=BODY_SIZE, fontname=BODY_FONT, fontweight='bold')

    # Plot 2: Errors Received per Stage
    rec_values = [error_reception[s] for s in stages]
    bars2 = ax2.barh(range(len(stages)), rec_values,
                     color=['#3498db', '#9b59b6', '#1abc9c', '#e74c3c', '#95a5a6'],
                     alpha=0.8, edgecolor='black', linewidth=1.5)
    ax2.set_yticks(range(len(stages)))
    ax2.set_yticklabels(stages, fontsize=BODY_SIZE, fontname=BODY_FONT)
    ax2.set_xlabel('Errors Received', fontsize=HEADING_SIZE, fontname=BODY_FONT, fontweight='bold')
    ax2.set_title('Error Reception by Stage', fontsize=HEADING_SIZE, fontname=BODY_FONT, fontweight='bold')
    ax2.grid(axis='x', alpha=0.3, linestyle='--')

    # Add value labels
    for i, (bar, val) in enumerate(zip(bars2, rec_values)):
        if val > 0:
            ax2.text(val + 0.5, i, str(int(val)),
                    va='center', fontsize=BODY_SIZE, fontname=BODY_FONT, fontweight='bold')

    # Add summary text
    total_propagations = sum(gen_values)
    fig.text(0.5, 0.02, f'Total Error Propagations: {total_propagations}',
             ha='center', fontsize=BODY_SIZE, fontname=BODY_FONT, style='italic')

    plt.tight_layout(rect=[MARGIN_NORMALIZED, MARGIN_NORMALIZED + 0.03,
                          1-MARGIN_NORMALIZED, 0.94])
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)'''

# Replace PAGE 5
del lines[page5_start:page5_end+1]
lines.insert(page5_start, new_visualization)

# Reconstruct source
new_source = '\n'.join(lines)
new_source_list = [line + '\n' for line in new_source.split('\n')]

# Update cell
nb['cells'][cell_idx]['source'] = new_source_list

# Save
with open('integration_paradox_demo.ipynb', 'w') as f:
    json.dump(nb, f, indent=2)

print("="*80)
print("REPLACED HEATMAP WITH BAR CHARTS")
print("="*80)
print()
print("✅ Removed problematic heatmap")
print("✅ Added clear bar chart visualization with 2 panels:")
print("   • Left: Errors Generated by each stage (horizontal bars)")
print("   • Right: Errors Received by each stage (horizontal bars)")
print("   • Color-coded by stage")
print("   • Value labels on each bar")
print("   • Total propagations count at bottom")
print()

# Validate
try:
    with open('integration_paradox_demo.ipynb', 'r') as f:
        test_nb = json.load(f)
    print("✓ Notebook JSON is valid")

    source = ''.join(test_nb['cells'][cell_idx]['source'])
    compile(source, '<cell>', 'exec')
    print("✓ Cell compiles successfully")
    print()
    print("✓ Bar chart visualization should render clearly")

except Exception as e:
    print(f"✗ Error: {e}")
    exit(1)

print("="*80)
